#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: Supports Basic Authentication for authenticating all API requests.
describedBy:
  headers: 
    Authorization:
      description: Base64-encoded "username:password"
      type: string  