api:
  id: "19372880"
  domain: "int-s-pc-itemmanagement-api-uat"
  
environment:
  id: "e0e4d0f7-b4d4-4628-8aea-4d854095ae87"
  
sftp:
  timeout: "30000"

system:
  #host: "pc-nonprod-dlb.lb.anypointdns.net" #--locally
  host: "internal-pc-nonprod-dlb.lb.anypointdns.net" #--deploying
  integrationServices:
    port: "443"
    timeout: "30000"
    basepath: "/int-s-glb-integrationservices-api-uat/api/v1"

wms:        
  configRef: "WMS_DB-config"
                    
awsSQS:
  createItem:
    arn: "arn:aws:sqs:eu-west-2:519093596938:uat_warehousing_pc_item_create_mule"
    queueURL: "https://sqs:eu-west-2.amazonaws.com/519093596938/uat_warehousing_pc_item_create_mule"
    dlqArn: "arn:aws:sqs:eu-west-2:519093596938:uat_warehousing_pc_item_create_dlq_mule"
    dlqQueueURL: "https://sqs:eu-west-2.amazonaws.com/519093596938/uat_warehousing_pc_item_create_dlq_mule"    
  updateItem:
    arn: "arn:aws:sqs:eu-west-2:519093596938:uat_warehousing_pc_item_update_mule"
    queueURL: "https://sqs:eu-west-2.amazonaws.com/519093596938/uat_warehousing_pc_item_update_mule"
    dlqArn: "arn:aws:sqs:eu-west-2:519093596938:uat_warehousing_pc_item_update_dlq_mule"
    dlqQueueURL: "https://sqs:eu-west-2.amazonaws.com/519093596938/uat_warehousing_pc_item_update_dlq_mule" 
  deleteItem:
    arn: "arn:aws:sqs:eu-west-2:519093596938:uat_warehousing_pc_item_delete_mule"
    queueURL: "https://sqs:eu-west-2.amazonaws.com/519093596938/uat_warehousing_pc_item_delete_mule"
    dlqArn: "arn:aws:sqs:eu-west-2:519093596938:uat_warehousing_pc_item_delete_dlq_mule"
    dlqQueueURL: "https://sqs:eu-west-2.amazonaws.com/519093596938/uat_warehousing_pc_item_delete_dlq_mule" 
    
awsSNS:
    globalErrorTopicArn: "arn:aws:sns:eu-west-2:519093596938:uat-warehousing-global-error"    