#%RAML 1.0 ResourceType
  description: <<getRecordListSummary>>
  get:
    description: <<getRecordListDescription>>
    is: [ success_list_200: {recordListType: <<getRecordListType>>, recordListExample: <<getRecordListExample>>}, 
         err_400,err_401,err_404,err_405,err_406,err_407,err_415,err_500,err_503,err_504  ]