#%RAML 1.0 ResourceType
    description: <<putRecordSummary>>
    put:      
      description: <<putRecordDescription>>
      body:
        type: <<putRecordType>>
        example: <<putRecordExample>>      
      is: [ success_200: {recordType: <<putRecordType>>, recordExample: <<putRecordExample>>},success_202: {recordExample: <<putOutputExample_202>>},nullvalue_204,err_400,err_401,err_404,err_405,err_406,err_415,err_500,err_503,err_504 ]
