#%RAML 1.0 Trait
    responses:
      200:
        description: This status code will be returned when the request has succeeded 
        body:
          application/xml:
            type: <<recordType>>
            example: <<recordExample>>