#%RAML 1.0 Trait
    responses:
      201:
        description: This status code will be returned when the request has succeeded and a new resource has been created as a result
        body:
          application/json:
            type: <<recordType>>
            example: <<recordExample>>