#%RAML 1.0 DocumentationItem
title: int-s-pc-itemmanagement-api
content: |
    #  API
    This API is the Items system layer that will specifically connect to a database and will be used to make create, update and delete order requests. The order status retrieve request will be sent to the Integration DB
    # Note
    This API will function two ways; synchronously and asynchronously. The synchronous function means that the corresponding process layer will be able to call this system layer directly. The asynchronous function means that all requests will be published to a topic, allowing the ability to send an immediate response to the consumer as well as handle a large volume of requests