#%RAML 1.0 Trait

headers:
  accessToken:
    description: Bearer token required for the underlying API
    type: string
    maxLength: 600
    minLength: 5
    required: true
    example: 3F2504E04F8911D39A0C