#%RAML 1.0 Library

traits: 

  err_400: !include traits/err_400.raml
  err_401: !include traits/err_401.raml
  err_403: !include traits/err_403.raml
  err_404: !include traits/err_404.raml
  err_405: !include traits/err_405.raml
  err_406: !include traits/err_406.raml
  err_407: !include traits/err_407.raml
  err_415: !include traits/err_415.raml
  err_500: !include traits/err_500.raml
  err_501: !include traits/err_501.raml
  err_503: !include traits/err_503.raml
  err_504: !include traits/err_504.raml
  err_509: !include traits/err_509.raml
  global_error_response: !include traits/global_error_response.raml