#%RAML 1.0 Library

resourceTypes:
  api_status: !include resourceTypes/api_status.raml
  get_mode_list: !include resourceTypes/get_mode_list.raml
  get_mode_single: !include resourceTypes/get_mode_single.raml
  get_mode_list_paged: !include resourceTypes/get_mode_list_paged.raml
  post_mode: !include resourceTypes/post_mode.raml
  post_mode_xml: !include resourceTypes/post_mode_xml.raml
  put_mode: !include resourceTypes/put_mode.raml
  delete_mode: !include resourceTypes/delete_mode.raml
  collection_types_json: !include resourceTypes/collection_types_json.raml
  collection_types_xml: !include resourceTypes/collection_types_xml.raml
  collection_types_xml_json: !include resourceTypes/collection_types_xml_json.raml