#%RAML 1.0 Trait
queryParameters:
  client_id:
   description: Client ID of authorized application registered at identity provider. 
   displayName: client_id
   example: Wsd45646345-56fgbhgfg-gfhjfg
   required: true
   type: string
  client_secret:
   description: Client secret of authorized application generated at identity provider.
   displayName: client_secret
   example: sdafgsadg34sdfsd54-sdfg
   required: true
   type: string
    